### ISSUE TITLE
Correctly hooked, but the Sidebar is just showing background and no widgets for the first sidebar created

### ISSUE THREAD

**Issue by Madderose** [JoryHogeveen/off-canvas-sidebars#97] opened 2020-07-26 16:18 UTC
## Description
Hi,
The first sidebar I created wasn't working (the widgets weren't displayed, just the background). It was first named by default "sidebar", which I changed to "sidebarfilter".
I populated it with even the simplest widget 'text' and it wasn't displaying anything (I checked the html code in the front-end, purged all cache, etc.)
I was starting to write this ticket, and I thought I should try to create a second sidebar with a different name, just in case.
I created "sidebarmobilefilter", after refreshing the widget page, the first off-canvas sidebar created disappeared from the "Widgets" space... But it is still present in the plugin in "Off-Canvas Sidebars" > "Sidebars." I selected the newly created sidebar after populating it with a "text" widget, and this one is actually showing in my front-end correctly. Both are configured similarly, and have the checkbox "enable" ticked.

## Specifications

  - Plugin Version: 0.5.6
  - WordPress Version: 5.4.2
  - Other plugins installed: WooCommerce 4.3.1, others.
  - Theme: StoreFront
  - Browser: Irrelevant

Thank you.

**Comment by JoryHogeveen** [comment] 2020-07-28 20:23
Hi @Madderose 

Sorry for my late reply, just came back from my holiday.

> after refreshing the widget page, the first off-canvas sidebar created disappeared from the "Widgets" space...

This is odd, I tried to reproduce but I cannot.. I have created several sidebars (widget areas) locally and all show up fine.

Do you have a link I can check?

Cheers! Jory

**Comment by JoryHogeveen** [comment] 2020-10-02 11:18
Closing issue due to no reply. Feel free to reopen if you still need help!

Cheers, Jory

**Closed by JoryHogeveen** 2020-10-02 11:18 UTC
