### ISSUE TITLE
Generatepress compability - some functions not working

### ISSUE THREAD

**Issue by kaktux** [JoryHogeveen/off-canvas-sidebars#91] opened 2020-05-19 14:53 UTC
Generatepress compability - some functions not working

Settings: all on preset - but:
website_before hook name -> wp_body_open
website_after hook name -> wp_footer

## Steps to reproduce the behavior:
1. Install Plugin
2. create Slidebar
3. add Slidebar with hook (Menu entry and widget entry same behaviour)
4. open slidebar
5. click anywhere on page
-> slidebar doesn't close although 
"Close sidebar when clicking on the site" is enabled /checked

## Expected behavior
Slidebar closes

## Specifications

  - Plugin Version: 0.5.5 
  - WordPress Version: 5.4.1
  - Other plugins installed: Autoptimize (deactivated), DSGVO All in one PRO for WP, GenerateBlocks, GP Premium, Gutenberg Forms, Off-Canvas Sidebars & Menus (Slidebars), Pages In Widgets, Rank Math SEO, TranslatePress 
  - Theme: Generatepress
  - Browser: Firefox 76.0.1
  - URL of where the bug occurs:
  - Location of hook placement (header.php and footer.php)

## Additional context
[Testpage](sandbox.acphis.com)

**Comment by JoryHogeveen** [comment] 2020-05-19 17:11
Hi @kaktux 

I've been testing for a while now and can't find what is causing this. I cannot reproduce this behavior locally or on my own projects so it must be something specific to your installation.

My only thought at this moment is that some part of that theme or other plugin is preventing the click event to come through.
This click event is done here: https://github.com/JoryHogeveen/off-canvas-sidebars/blob/master/js/off-canvas-sidebars.js#L403-L410

Can you confirm this bug occurs with ONLY GeneratePress and this plugin active?

**Comment by kaktux** [comment] 2020-05-20 11:50
yes - i just tested with disabling all plugins except gp premium and slidebars. Verified on my hosted installation and on my sandbox on a virtual machine with different browsers.

I also clicked and tested through all options to see - and:

when i select in sidebar tab: "override global settings" with "Close sidebar when clicking on the site" enabled - it works (basically i just checked override and leaved it as it was). 
Although this is already checked in the settings tab. 

Tested also on different browsers, mobile, pc
Beforehand and afterwards i also switched between generatepress and twenty twenty. Before: both the error - after: both working.

Weird. But hey.

I leave it as it is for some time if you would like to have a look.
I did make this one change for the lower sidebar.
The upper one still is the same (so only the override global settings not checked).

**Comment by JoryHogeveen** [comment] 2020-05-21 12:58
Hi @kaktux 

I see, good find! I think this bug was there since 0.5.0 already. I could replicate the differences in overwriting global settings or not on my local installation.
Please check #92 for changes and let me know if that fixes your issues as well!

Cheers, Jory

**Comment by kaktux** [comment] 2020-05-21 13:38
Yes - the changes in the 2 files make the global override unnecessary - as global is working now without issues. Can confirm the fix.

thx a lot.

**Comment by JoryHogeveen** [comment] 2020-05-21 13:55
Thanks for your quick confirmation!
This patch will be included in the next release, no ETA yet, sorry!

**Closed** 2020-06-30 12:35 UTC
Labels: bug
