### ISSUE TITLE
Main content area isn't responsive?

### ISSUE THREAD

**Issue by mushbrain666** [JoryHogeveen/off-canvas-sidebars#115] opened 2023-06-26 00:25 UTC
Am I understanding correctly that by design; when the sidebar is open it pushes main content area out of frame, rather than the content area resizing - paragraphs get shorter, images shrink, etc. ?

Using Generatepress Element Custom Hook with `ocs_custom_content_sidebar_offcanvas`  and its working amazing other than the content area not being responsive. 

`generate_before_header` / `generate_after_footer` work as well as `wp_body_open` / `wp_footer`, not sure if that makes a difference. 

Not seeing any difference with the options in _Compatibility for fixed elements_.

Also not seeing responsive results for _Style (Animation)_ other than overlay, which at least confirms the selector. 

So at this point I'm wondering if it's not even the desired behavior. 

For reference, I'm trying to achieve something like https://davidde.github.io/sidebars/

Thanks very much for any guidance.

**Comment by JoryHogeveen** [comment] 2023-06-28 08:43
Hi @mushbrain666 

Currently there are indeed 4 types of animations available but the animation you are referring to is indeed not part of this plugin at this point. I did work on such an animation for some time but didn't have the time/resources to continue with this (you are actually the first to ask for such a feature).
https://github.com/JoryHogeveen/off-canvas-sidebars/pull/68

You can test it out if you want!
Cheers, Jory

**Comment by JoryHogeveen** [comment] 2023-09-07 11:50
Closing topic as a duplicate of #64

**Closed by JoryHogeveen** 2023-09-07 11:50 UTC
Labels: feature
